# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: UX Lift
email: m@kevan.tv
description: > # this means to ignore newlines until "baseurl:"
  A collection of the best articles, resources, books and tools, covering every aspect of the UX and design process.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.uxlift.org" # the base hostname & protocol for your site, e.g. http://example.com
logo: /assets/site/uxlift-logo-card.jpg
lang: en_GB
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

encoding: utf-8
permalink: pretty
exclude:
  - Gemfile
  - Gemfile.lock
  - scripts

sass:
  sass_dir: _sass

page_gen-dirs: true

collections:
  topics:
    output: true
    permalink: /topics/:path/
  topic-categories:
    output: true
    permalink: /topics/:path/
  books:
    output: true
    permalink: /books/:path/
  tools:
    output: true
    permalink: /tools/:path/
  tool-categories:
    output: true
    permalink: /tools/:path/
  articles:
    output: true
    permalink: /articles/:path/
  design-systems:
    output: true
    permalink: /design-systems/:path/
  design-principles:
    output: true
    permalink: /design-principles/:path/
  plugin:
    output: true
    permalink: /plugins/:path/
  courses:
    output: true
    permalink: /courses/:path/
  course-types:
    output: true
    permalink: /courses/:path/
  directory:
    output: true
    permalink: /directory/:path/
  directory-types:
    output: true
    permalink: directory/:path
  resources:
    output: true
    permalink: /resources/:path
  resource-types:
    output: true
    permalink: /resources/:path

defaults:
  -
    scope:
      path: ""
      type: topics
    values:
      layout: default
  -
    scope:
      path: ""
      type: topic-categories
    values:
      layout: listing
  -
    scope:
      path: ""
      type: resources
    values:
      layout: resource
  -
    scope:
      path: ""
      type: resource-types
    values:
      layout: resource-listing
  -    
    scope:
      path: ""
      type: books
    values:
      layout: book
  -
    scope:
      path: ""
      type: tools
    values:
      layout: tool
  -
    scope:
      path: ""
      type: design-systems
    values:
      layout: tool
  -
    scope:
      path: ""
      type: design-principles
    values:
      layout: tool
  -
    scope:
      path: ""
      type: plugin
    values:
      layout: tool
  -
    scope:
      path: ""
      type: courses
    values:
      layout: course
  -
    scope:
      path: ""
      type: directory
    values:
      layout: directory
  -
    scope:
      path: ""
      type: course-types
    values:
      layout: course-listing
  -
    scope:
      type: directory-types
    values:
      layout: org-listing